"""empty message

Revision ID: 83f59531395c
Revises: 
Create Date: 2019-08-10 14:47:44.348883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f59531395c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('create_time', sa.Integer(), nullable=True))
    op.add_column('book', sa.Column('status', sa.SmallInteger(), nullable=True))
    op.add_column('gift', sa.Column('create_time', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('create_time', sa.Integer(), nullable=True))
    op.add_column('wish', sa.Column('create_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish', 'create_time')
    op.drop_column('user', 'create_time')
    op.drop_column('gift', 'create_time')
    op.drop_column('book', 'status')
    op.drop_column('book', 'create_time')
    # ### end Alembic commands ###
